### ISSUE TITLE
Wahl eines Frontend Frameworks 

### ISSUE THREAD

**Issue by Marius998** [Marius998/EPWS2019GuenthnerHammer#1]
Framework letztes Projekt :  **Vue.js** 

Im Rahmen des WPF Webdevelopment letztes Semester haben wir uns bereits mit Vue.js vertraut gemacht, da es als Grundlage unsere Anwedung diente. 
Nach weiterer Recherche in Richtung Vue haben wir weitere Frameworks gefunden, welche auf Vue basieren.

**Comment by Felix2019** [comment]
Wir haben für uns Vue Native entschieden.
